sudo: required
services:
  - docker

before_script:
  - export NODE_ENV=test
  - docker-compose -f docker-compose-trav.yml up --build -d

script:
  - docker-compose -f docker-compose-trav.yml run details-catalog npm test

after_script:
  - docker-compose down